"""
Phase 1 placeholder for the LangGraph agent pipeline.

`generate_mock_report` returns data shaped exactly like the real pipeline
will in Phase 2 (see models.AnalysisReport), so the frontend and the
deployment can be validated end-to-end before any agent, data source, or
LLM call exists. When Phase 2 lands, this function is replaced by a call
into backend/graph.py — nothing else in the app should need to change.
"""

from __future__ import annotations

import random
from datetime import datetime, timezone

from models import AnalysisReport, TradeIdea

AGENTS = ["News", "Fundamentals", "Technical", "OptionsFlow", "Macro", "Risk"]
DIRECTIONS = ["long", "short", "options_spread"]


def generate_mock_report(tickers: list[str]) -> AnalysisReport:
    trades: list[TradeIdea] = []

    for symbol in tickers[:3]:
        supporting = random.sample(AGENTS, k=random.randint(2, 4))
        dissenting = [a for a in AGENTS if a not in supporting][:2]

        trades.append(
            TradeIdea(
                symbol=symbol.upper(),
                direction=random.choice(DIRECTIONS),
                thesis=(
                    f"Placeholder thesis for {symbol.upper()}. This will be "
                    "generated by the Portfolio Manager judge agent once the "
                    "LangGraph debate pipeline (Phase 2) is wired in."
                ),
                confidence=round(random.uniform(0.5, 0.9), 2),
                key_risks=[
                    "Placeholder risk — real risks come from the Risk agent",
                    "Placeholder risk — real risks come from the Bear debate",
                ],
                supporting_agents=supporting,
                dissenting_agents=dissenting,
            )
        )

    return AnalysisReport(
        top_trades=trades,
        market_context=(
            "This is mocked market context. Phase 1 validates the API "
            "contract and deployment; no live data or LLM calls are made yet."
        ),
        generated_at=datetime.now(timezone.utc),
        is_mocked=True,
    )
